name: Deploy to Prod

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: elixir:1.10.2-slim
    services:
      postgis:
        image: mdillon/postgis:11
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOST: "/"
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        chmod -R 777 script/dependencies.sh
        sh script/dependencies.sh
    - name: Precheck
      run: |
         chmod -R 777 script/test.sh
         sh script/test.sh
      env:
       POSTGRES_HOST: "postgis"
       POSTGRES_PORT: ${{ job.services.postgis.ports[5432] }}
    - name: Deployment
      env:
        DEPLOY_STAGE: bangtan
        GIGALIXIR_EMAIL: ${{ secrets.GIGALIXIR_EMAIL}}
        GIGALIXIR_PASS: ${{secrets.GIGALIXIR_PASSWORD }}
        SSH_KEY: ${{ secrets.SSH_KEY}}
        SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC }}
      run: |
        chmod -R 777 script/deploy.sh
        bash script/deploy.sh
